#!/usr/bin/env ruby

# Usage - ./sample-wallpaper | osascript

picture = File.absolute_path Dir.entries(".").select{|f| f.match(".jpg") }.sample
puts "tell application \"System Events\" to set picture of every desktop to \"#{picture}\""
